# Generated by Django 3.1.1 on 2021-02-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapplication', '0002_auto_20210219_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='phonenumber',
            field=models.CharField(max_length=50),
        ),
    ]
